name: plot_gget_map
on:
  schedule:
    - cron: "0 16 * * *"
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
        
      - uses: actions/cache@v2
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install Python dependencies
        run: |
          python -m pip install -r requirements.txt
          
      - name: Execute Python code
        run: python map_gget_users.py ${{ secrets.GGET_PROPERTY_ID }} ${{ secrets.FERNET_KEY }}
      
      - name: Commit and push new plot
        run: |-
          git config user.name "Plot from CI"
          git config user.email ""
          git status
          git add gget_user_map.png
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
